### ISSUE TITLE
Missing Types?

### ISSUE THREAD

**Issue by RobbieLD** [RobbieLD/github-portfolio#3]
@a-jackson Any ideas why in the vuex branch which I've just pushed to, it doesn't like the CreateProxy in the NavBar.vue when it works fine in the store.ts. I've mentioned you in a comment there if it helps you find it.

**Comment by a-jackson** [comment]
I think it's because CreateProxy is static. It doesn't exist on the UserProxy instance although I think that should work anyway. When I try to import the VuexModule from vuex-class-component though I get an error that it cannot find the typings for that module even though they are there.

It doesn't complain when I build either way though so maybe it's actually just an issue with the vs code extension for vue files?

**Comment by RobbieLD** [comment]
I've fixed it by re-writing the whole store in the manner the author of that library suggests. Now it works correctly and we get type checking and auto complete. 

If you look in NavBar.vue now though you will see the once draw back. I've gone for a modules approach so we can make more vuex modules and easily include them so it's very extensible. What doesn't work is mapGetters. They do we in as much as it works correctly inside methods in the script part of the component but it doesn't seem to be reactive for binding in the template. So making computed props for that is the only way I can see around that. One question though on that front, do we need to define their return type such as string (or just leave it default to any) and if so do we need to make them `private get name(): string | undefined` or in the return for the prop coalesce to an empty string like `return vxm.user.gitUser.name || ''; `
